export const ERROR_CODES = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  FOREIGN_KEY_ERROR: 'FOREIGN_KEY_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
};